### ISSUE TITLE
lazy Iterable<Element> which discards subtree

### ISSUE THREAD

**Issue by mkienenb** [jhannes/eaxy#9]
Event driven is annoying. One alternative is to use a lazy Iterable<Element>. The syntax could be something like this:

for (Element element : Xml.iterate(someReader).find("foo", "bar", "baz")) {
}

The element contains a full subtree but eaxy would discard it when Iterator.next() is called.

This feature is of course most useful for documents that could be thought of as consisting of several sub-documents.

**Comment by jhannes** [comment]
A very late update on this one: I added functionality like this:

`ElementFilters.create("...", "p").iterate(new StringReader(xml.toXML())))`

(In order to get it to make sense, I had to put the Reader last).

I've added that uses this for a file of almost 100 MB to show that it is performant and keeps memory consumption down: https://github.com/jhannes/eaxy/blob/master/src/test/java/org/eaxy/SampleMedicationFilePerformanceTest.java
